### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Suparat-Scheu** [Rappsilber-Laboratory/build_xiview#91]
Hi! I'm trying to analyse my data but got the error message following ; 

log id: gnvv5kgj7hrkipqfn1ih0nmsj3_1661331176.log (include this in the github issue)
error type: Error
message: invalid literal for float(): 1,005
id: undefined

Could anyone help me point out where to fix ? 
Thank you

**Comment by colin-combe** [comment]
i think its probably because you have commas in the number fields of a csv file you uploaded? It doesn't like that. Try with decimal points marked with a "." ?

**Comment by Suparat-Scheu** [comment]
So far I noticed the commas in the number fields in the first analysis and I didn't modify my first file after I got the results.  The analysis did work with E.coli  See this data file: 

[20220819_Ecoli_xiSEARCH_2nd_run_Xi1.7.6.7_CSM_xiFDR2.1.5.5.csv](https://github.com/Rappsilber-Laboratory/xiView_container/files/9414825/20220819_Ecoli_xiSEARCH_2nd_run_Xi1.7.6.7_CSM_xiFDR2.1.5.5.csv)

 So I did the same with P. vulgatus but it showed up error I mentioned. 
[Exp02_Pvulgatus_1mM_BS3_Xi1.7.6.7_CSM_xiFDR2.1.5.5.csv](https://github.com/Rappsilber-Laboratory/xiView_container/files/9414805/Exp02_Pvulgatus_1mM_BS3_Xi1.7.6.7_CSM_xiFDR2.1.5.5.csv)

Could you point out which column I should fix? 
Thank you

**Comment by colin-combe** [comment]
>  which column I should fix?

the comma was being used as a thousands separator (in all columns i think) but it was in the PepPos columns that it particularly didn't like it.
i fixed it in all of them:
[Exp02_Pvulgatus_1mM_BS3_Xi1.7.6.7_CSM_xiFDR2.1.5.5_2.csv](https://github.com/Rappsilber-Laboratory/xiView_container/files/9415039/Exp02_Pvulgatus_1mM_BS3_Xi1.7.6.7_CSM_xiFDR2.1.5.5_2.csv)

could this have happened because of saving it from Excel?

**Comment by Suparat-Scheu** [comment]
Thank you Colin for a fixed file. 
Hmm.. I don't think so because I did not modify the file before uploading in the Xi-view.

**Comment by colin-combe** [comment]
> I don't think so because I did not modify the file before uploading in the Xi-view
 
 Ok. So, it came out of xiFDR this way? (Just double checking this.)
 ( @lutzfischer )

**Comment by Suparat-Scheu** [comment]
Hi Coli,
I took the data directly from the folder called "FDR_rpfdr5.0" after I proceed with Xi-Search.  I go this data because I clicked on " do FDR" on the parameter tab so I didn't perform the analysis in XiFDR.    As a new user, would you recommend to process the data from Xi-search to Xi-FDR again even I already selected  "do FDR" in the parameter tab of Xi-search? 
Thank you

**Comment by colin-combe** [comment]
hi - yes, it seems other people have had this problem also.

it should be possible to remove the commas with the 'number format' settings in your spreadsheet tool

the FDR you did should be fine i think (though xiFDR might remove those commas), but xiFDR does provide some more options about how the FDR is done

**Comment by Suparat-Scheu** [comment]
Thank you Colin. 

I have another issue that there is no information when I look at the spectrum view.  It show a blank page on spectrum view. Could you point out what is the reason? I actually did upload mgf files already.
