### ISSUE TITLE
Error: mzidentML file does not specify fragment ions

### ISSUE THREAD

**Issue by Suparat-Scheu** [Rappsilber-Laboratory/build_xiview#92]
Hi, 
I got another message when I try to upload .mzid file 

log id: gnvv5kgj7hrkipqfn1ih0nmsj3_1662128916.log (include this in the github issue)
warning type: IonParsing
message: mzidentML file does not specify fragment ions.
id: SIR_12; SIR_12; SIR_103; SIR_103; SIR_263; SIR_263; SIR_303; SIR_303; SIR_331; SIR_331; SIR_381; SIR_381; SIR_389; SIR_389; SIR_486; SIR_486; SIR_534; SIR_534; SIR_626; SIR_626; SIR_642; SIR_642; SIR_817; SIR_817; SIR_830; SIR_830; SIR_833; SIR_833; SIR_935; SIR_935; SIR_939; SIR_939; SIR_943; SIR_943; SIR_994; SIR_994; SIR_1018; SIR_1026; SIR_1026; SIR_1069; SIR_1069; SIR_1120; SIR_1120; SIR_1248; SIR_1248; SIR_1255; SIR_1255; SIR_1281; SIR_1281; SIR_1330 ...

could you suggest how to fix this? 

Thank you 
Suparat

**Comment by colin-combe** [comment]
hi,
its a bug/flaw in our mzIdentML parser. 
It's OK to ignore the "error", but do pick the correct ions searched for (you should see a dialog asking for this).
The ion series searched for should be specified in the AdditionalSearchParams in the mzIdentML, but even if they are there they are getting ignored. 
The bug will go away when the parser is updated but that is likely to be a couple of months away.
cheers,
colin

**Comment by Suparat-Scheu** [comment]
I see. thank you Colin
