### ISSUE TITLE
Histrogram: modification count

### ISSUE THREAD

**Issue by Suparat-Scheu** [Rappsilber-Laboratory/build_xiview#93]
Hi, 
I'm try to understand the histogram data based on my data, what is the meaning of the modification count 1,2, 3,4, 5 on X axis. why it shows only 5? 
could you explain how to interpret the modification data ? what is the good range? i.e between 0-1? 
As a new user, could you recommend the resource to read? 
Thank you 
Suparat
![Screenshot 2022-09-07 132709](https://user-images.githubusercontent.com/111968232/188869017-4b12444f-5fd2-499c-8608-a76fa21c48e4.png)

**Comment by colin-combe** [comment]
the 'modification count' should be the maximum number of modifications on either of the crosslinked peptides in a match.
So if you hover the mouse over the '3' bars then those matches where 3 is the most modifications in an identified peptide will be highlighted and if you click they will be selected. 

i can see that it's a bit confusing, please let me know if it looks broken 

i see there's a bug in that the colours used aren't shown in the labels (at the bottom)
