### ISSUE TITLE
Missing Cross-links

### ISSUE THREAD

**Issue by Lilka01** [Rappsilber-Laboratory/build_xiview#95]
Hello,

a week ago, I exported some XL data from MeroX, and everything worked fine. However, when I returned to the same data today, some XLs were missing (despite working on the same data). This issue occurred with all my data.
Additionally, when I imported a pdb file with an identical sequence, the XL distance was not computed for some XLs (not only XLs involving the N-terminus).
Could someone explain to me, please, what has happened?

Thanks!

**Comment by colin-combe** [comment]
Hi,
OK, I've made some mistake...
I've reverted it to the version it was a week ago - are things working fine again?
cheers,
Colin

**Comment by colin-combe** [comment]
are you able to share the file you uploaded so I can use it for testing?
(email it if you prefer - colin.combe@ed.ac.uk)

re. the  cross-link distance even when the N-terminus is involved, i'll add this to the list of feature requests,
have a nice day too,
C
